### ISSUE TITLE
Fix typo in documentation under Authority Records

### ISSUE THREAD

**Issue by sarah-mason** [artefactual/atom-docs#114]
**Version of documentation:** 2.5
**Section:** Authority Records
**Link:** https://www.accesstomemory.org/en/docs/2.5/user-manual/add-edit-content/authority-records/#authority-records

**Location:** 1st paragraph
**Sentence with error:** "Typically, authority records contain information about the authorized form of name and other forms of name by which the actor is known, dates of existence, relevant adminstrtive or biographical history details, and other contextual information; additionally, roles in events and relationships with archival materials are also captured and expressed."

**Error:** "adminstrtive" 
**Suggested fix**: "administrative"

**Comment by fiver-watson** [comment]
Fixed in https://github.com/artefactual/atom-docs/commit/28a8af4cc64508d6881cc5b6cc36204ee139e87b
