### ISSUE TITLE
Delete stray text from linux installation instructions

### ISSUE THREAD

**Issue by rpearcemoses** [artefactual/atom-docs#115]
Delete phrase "code content" in both Xenial and Bionic installation instructions under Elasticsearch.  (Bionic line 72, Xenial line 82).

**Comment by fiver-watson** [comment]
Fix merged in commit https://github.com/artefactual/atom-docs/commit/da3bd8ec9af4a2fbcd559bca07a25adb89090539

Thanks @rpearcemoses !
