### ISSUE TITLE
Remove mention(s?) of Transifex from documentation

### ISSUE THREAD

**Issue by fiver-watson** [artefactual/atom-docs#117]
**Documentation version**

2.5

**Location in docs**

* https://www.accesstomemory.org/docs/2.5/user-manual/translate/multilingual-design-principles/#multilingual-design-principles
* https://www.accesstomemory.org/docs/2.5/user-manual/translate/translate-content/
* https://www.accesstomemory.org/docs/2.5/user-manual/translate/translate-interface/
* https://www.accesstomemory.org/docs/2.5/user-manual/administer/settings/#add-remove-languages

**Issue encountered and recommended fix**

* Transifex is mentioned by name
* We should remove these
* Instead, we should keep the reference general and not mention a specific platform where possible. Where one is needed, update to Weblate.

**Comment by corinnemrogers** [comment]
Fixed; commit d5f8ce2
