### ISSUE TITLE
Problem: Publishing archival description note is out of date

### ISSUE THREAD

**Issue by ross-spencer** [artefactual/atom-docs#144]
The correct way to publish a description is [here](https://www.accesstomemory.org/en/docs/2.5/user-manual/add-edit-content/archival-descriptions/#to-publish-an-existing-archival-description)

But in the same page on 2.5 we have a note ([here](https://github.com/artefactual/atom-docs/blob/cc2bb4f1453ea22a3c74b93bd08c221896328523/user-manual/add-edit-content/archival-descriptions.rst)):

![image](https://user-images.githubusercontent.com/1880412/80824610-cdb44280-8bac-11ea-9e23-b41899762552.png)

If a user is looking for the publish button in the administration area in 2.5 they will not find it.

**Comment by fiver-watson** [comment]
Good catch, @ross-spencer ! Fixed in https://github.com/artefactual/atom-docs/commit/e0fca5148788ae5d8b4a1520bf56f5c0209ba1a5; will cherry-pick to 2.6 as well.

**Comment by fiver-watson** [comment]
Cherry-picked to 2.6 in https://github.com/artefactual/atom-docs/commit/2f0110499b34d675c0fd622e2b4ec84d5712c940
