### ISSUE TITLE
Add docs for ability to add multiple identifiers to accession records

### ISSUE THREAD

**Issue by evelynPM** [artefactual/atom-docs#145]
**Version of the documentation**

2.5

**Link to Redmine ticket (if applicable)**

* https://projects.artefactual.com/issues/13254

**Page (and section, if applicable) where the issue occurs**

* https://www.accesstomemory.org/en/docs/2.5/user-manual/add-edit-content/accessions/#add-new-accession

**Suggested fix**

I think this just needs an updated screenshot.

**Comment by fiver-watson** [comment]
fixed in https://github.com/artefactual/atom-docs/commit/e4d1dd7e57fcf6c4b9806b075fd7fc77a308084d
