### ISSUE TITLE
Add docs for ability to associate accessions with physical storage

### ISSUE THREAD

**Issue by evelynPM** [artefactual/atom-docs#146]
**Version of the documentation**

2.6

**Link to Redmine ticket (if applicable)**

* https://projects.artefactual.com/issues/13268

**Page (and section, if applicable) where the issue occurs**

* https://www.accesstomemory.org/en/docs/2.5/user-manual/add-edit-content/physical-storage/#link-physical-storage

**Suggested fix**

Update "Link physical storage" section to describe ability to link storage to accessions.

**Comment by fiver-watson** [comment]
Fixed in https://github.com/artefactual/atom-docs/commit/2b634651866c8a2d79b7fa13dcd722831f234667
