### ISSUE TITLE
Add new docs for physical storage location CSV report

### ISSUE THREAD

**Issue by evelynPM** [artefactual/atom-docs#147]
**Version of the documentation**

2.6

**Link to Redmine ticket (if applicable)**

* https://projects.artefactual.com/issues/13269

**Page (and section, if applicable) where the issue occurs**

* https://www.accesstomemory.org/en/docs/2.5/user-manual/reports-printing/create-physical-storage-report/#create-physical-storage-report

**Suggested fix**

Add new section.

**Comment by fiver-watson** [comment]
Added in https://github.com/artefactual/atom-docs/commit/106059e7f43969723cb545fbcd93889635cd65d0
