### ISSUE TITLE
Add docs for ability to export digital objects via the clipboard

### ISSUE THREAD

**Issue by evelynPM** [artefactual/atom-docs#170]
**Version of the documentation**

2.7

**Link to Redmine ticket (if applicable)**

* https://projects.artefactual.com/issues/13395

**Page (and section, if applicable) where the issue occurs**

* https://www.accesstomemory.org/en/docs/2.7/user-manual/access-content/clipboard/#clipboard, 

**Suggested fix**

Add section entitled "Include digital objects in clipboard exports."

**Comment by evelynPM** [comment]
Also need an edit to https://www.accesstomemory.org/en/docs/2.7/user-manual/administer/settings/#clipboard-settings

**Comment by fiver-watson** [comment]
Addressed via https://github.com/artefactual/atom-docs/pull/175 -  closing
