### ISSUE TITLE
Problem: 2.7 installation docs currently install wrong version of Java

### ISSUE THREAD

**Issue by fiver-watson** [artefactual/atom-docs#198]
**Documentation version**

2.7

**Relevant documentation pages**

* https://www.accesstomemory.org/docs/2.7/admin-manual/installation/ubuntu/

**Related resources**

* User forum thread: https://groups.google.com/g/ica-atom-users/c/sYqeIq30KdE/m/OI7B4pVcBgAJ
* Redmine issue ticket: https://projects.artefactual.com/issues/13522

**Issue description**

In 2021 we discovered that using the Java version that ES 5.6 recommends (`openjdk-8-jre-headless`) causes finding aid generation to fail (see issue link above). Testing on the issue confirmed that using `openjdk-11-jre-headless` instead resolves the issue, and still works with ES despite it not being the recommended Java version. 

However, this change was never added to the 2.7 installation documentation. Recently a user in the forum encountered this issue following our installation instructions (see forum link above).

**Recommended solution**

We need to update the Java installation instructions in the 2.7 installation documentation in the following section: 

* https://www.accesstomemory.org/docs/2.7/admin-manual/installation/ubuntu/#elasticsearch

A developer should confirm what the correct / best command should be. Note that currently we are also installation `apt-transport-https`. The 2.5 documentation (which also used ES 5.6) has a command [here](https://www.accesstomemory.org/en/docs/2.5/admin-manual/installation/linux/ubuntu-bionic/#elasticsearch) to install the desired Java version, but I am not personally clear whether or not we could still install `apt-transport-https` or not, nor whether we need to install the ppa first or not. These elements should be confirmed before the docs are updated.

**Comment by fiver-watson** [comment]
From @sbreker : 

The correct commands in the 2.7 documentation should be: 

```
sudo apt-get update
sudo apt install openjdk-11-jre-headless software-properties-common apt-transport-https
```

**Comment by mamedin** [comment]
PR #203 merged
