### ISSUE TITLE
Overview - core_entity_types.png is out of  date

### ISSUE THREAD

**Issue by kieranjol** [artefactual/atom-docs#214]
It appears that the entity types here: https://www.accesstomemory.org/en/docs/2.7/_images/core-entity-types.png
are out of date and do not align with the list of entity types in the text: https://www.accesstomemory.org/en/docs/2.7/user-manual/overview/entity-types/

**Comment by fiver-watson** [comment]
Hi @kieranjol , thanks again for mentioning this. I've added an updated image here: 

* https://www.accesstomemory.org/en/docs/2.7/_images/core-entity-types.jpg

It may take a bit for us to propagate the change to the website - I see we have some automated test issues to resolve.  I also added the following comments on the PR, which I'll copy here for reference: 

> Note that the documentation still doesn't exactly match all the entities shown in the diagam - now, rather than showing far less, the diagram actually shows more than what is described in the Entity Types documentation, including Events, Donors, etc.
> 
> Despite this, it's a more accurate diagram; the Entity types page can be further updated later if desired but still has the key entities described; and there's not a separate docs page on events (since it's more of an internal design term than something shown to end users).

Anyway, hope this is an improvement for you. Thanks again!

**Comment by kieranjol** [comment]
This is great, thank you!

K
