### ISSUE TITLE
AtoM docs for BS5 theme migration

### ISSUE THREAD

**Issue by anvit** [artefactual/atom-docs#237]
AtoM 2.8 will include a banner that mentions Bootstrap 2 deprecation, and points to a manual page. See https://github.com/artefactual/atom/issues/1642 for details about the deprecation banner.

The docs page/section could potentially be added under the admin theming page under a section called BS2 update: https://www.accesstomemory.org/en/docs/latest/admin-manual/customization/theming/#bs2-update.

Also, the [User Manual > Administer > Themes](https://accesstomemory.org/en/docs/2.7/user-manual/administer/themes/) section should be updated to say that arDominionB5Plugin is the default, and add a notice informing them about BS2 themes being deprecated, and pointing to the migration page/section.

**Comment by melaniekung** [comment]
The following docs refer to BS2 instructions for upgrading/creating a custom theme. We should include a notice that specifies that these instructions are for BS2 themes, which will be deprecated in release 2.8, and also add new instructions for the BS5 process:

[Admin Manual > Installation > Upgrading](https://accesstomemory.org/en/docs/2.7/admin-manual/installation/upgrading/#upgrading-with-a-custom-theme-plugin)
[Admin Manual > Customization > Theming](https://accesstomemory.org/en/docs/2.7/admin-manual/customization/theming/#create-a-custom-theme)
