### ISSUE TITLE
Problem: there are spelling errors

### ISSUE THREAD

**Issue by eviau-artefactual** [artefactual/atom-docs#257]
Hello :sparkles: 

I was looking at automated ways to improve the docs.

There is a Sphinx spellchecker: https://sphinxcontrib-spelling.readthedocs.io/

Would we be interested in using it ? I will open a PR setting it up to allow you to look at potential results enabled by this tool.

**Comment by eviau-artefactual** [comment]
Looking at the results, some of them are useful, like this typo: https://github.com/artefactual/atom-docs/actions/runs/7761741254/job/21170791245#step:6:1875

Most of them are technical terms... I am not sure what to do with this for now. If you do decide that this is worthwhile I can make a proper PR and (try to) correct most spelling mistakes, for a given locale.

**Comment by melaniekung** [comment]
hi edith! i think this would be very useful and would love to see a PR for this! thank you for looking into it!

**Comment by eviau-artefactual** [comment]
The PRs #269  and #265 should have fixed all existing typos in the atom-docs repo.

The PR #263 enables spellchecking for the future.

we can add new words to the `spelling_wordlist.txt` file as needed.

Thanks everyone :sparkles:
