### ISSUE TITLE
Problem: The items per page limit will need to be updated in the docs

### ISSUE THREAD

**Issue by anvit** [artefactual/atom-docs#266]
AtoM's next release (tentatively 2.8.1) will be updating the default items per page limit to 8000. This will need to be updated in the docs.  

[User Manual > Administer > Setting > Items per page](https://github.com/artefactual/atom-docs/blob/13429f7d3b03f07ed4ff558d10c0d37a94854412/user-manual/administer/settings.rst#L2890)

**Comment by Jennoit** [comment]
I can comment but not self assign (which is okay, just discussing settings here as part of contributors' club).

**Comment by eviau-artefactual** [comment]
I think we can now close this issue given https://github.com/artefactual/atom-docs/commit/d238a43ba67e531c298316bc88f48983f23b0c06
