### ISSUE TITLE
PHP-FPM restart instructions on Debug page should be version-specific

### ISSUE THREAD

**Issue by fiver-watson** [artefactual/atom-docs#48]
**Version of the documentation**

2.4, 2.5

**Location: Manual, Page (and section, if applicable) where the issue occurs**

* https://www.accesstomemory.org/en/docs/2.4/admin-manual/maintenance/debug/#using-qubit-dev-php

**Description of the issue**

Debug mode page tells users to restart PHP-FPM, but only includes instructions for doing so for PHP5. 

**Suggested fix**

Update restart instructions to include specific instructions for 14.04 and 16.04. E.g.:

```
**Ubuntu 14.04:**

.. code-block::bash
   
   sudo service php5-fpm restart

**Ubuntu 16.04:**

.. code-block:: bash
   
   sudo systemctl restart php7.0-fpm
```

**Comment by corinnemrogers** [comment]
Change has been made as per suggestion to:

- https://www.accesstomemory.org/en/docs/2.4/admin-manual/maintenance/debug/#using-qubit-dev-php

for 2.4, 2.5
