### ISSUE TITLE
Delete digital object from command line

### ISSUE THREAD

**Issue by corinnemrogers** [artefactual/atom-docs#49]
**Version of the documentation**

New content to add to 2.4, 2.5

**Page (and section, if applicable) where the issue occurs**

- https://www.accesstomemory.org/en/docs/2.4/admin-manual/maintenance/cli-tools/#maintenance-cli-tools

**Description of the issue**

Digital objects can be deleted from the command line

**Suggested fix**

***Delete a digital object***

You can do this if you have the slug of the related description. The basic syntax of the command is:

```php symfony digitalobject:delete slug-of-description```

Where `slug-of-description` represents the target record.

***Deleting digital objects from a complex hierarchy***

The task also has one option, that can be used to delete all digital objects in a hierarchy. You can do this using the CLI task: `digitalobject:delete`

So you would find the slug for the top level description for which you wanted to remove the digital objects (and for its descendants), and then you could run:

```php symfony digitalobject:delete --and-descendants your-top-level-description-slug```

Where `your-top-level-description-slug` represents the slug of the parent record.

NOTE: this task will not update the search index, so you need to run `search:populate` afterwards.

**Comment by fiver-watson** [comment]
Also added to 2.5 branch: https://github.com/artefactual/atom-docs/commit/6a06d2c4cda098e6947d517e99782c3b64ec0288

**Comment by fiver-watson** [comment]
Oops, here's the 2.6 branch commit: https://github.com/artefactual/atom-docs/commit/4aca2e133ebe2346f98b94d3e2f932ce73e16933
