### ISSUE TITLE
Test CSV accession imports and updates and update documentation

### ISSUE THREAD

**Issue by corinnemrogers** [artefactual/atom-docs#50]
**Version of the documentation**

New content for 2.4, 2.5

**Link to User Forum question**

Related user forum thread: 

- https://groups.google.com/d/msg/ica-atom-users/w3EYlb9VkLA/gurkaxQOCAAJ

**Page (and section, if applicable) where the issue occurs**

- https://www.accesstomemory.org/en/docs/2.4/user-manual/import-export/csv-import/

**Description of the issue**

Currently docs don't note anything about being able to update accessions via CSV import 

**Suggested fix**

It seems like maybe matches on accession number will currently import and update, rather than throwing an error or skipping, etc. Do some testing, and add notes to the docs.

**Comment by fiver-watson** [comment]
Fixed in https://github.com/artefactual/atom-docs/commit/caa6fe9ef8538b9ea435370bfa238a88b55d3eb2
