### ISSUE TITLE
Links to ISAAR-CPF standard in Authority records page are broken

### ISSUE THREAD

**Issue by testy-mctest** [artefactual/atom-docs#51]
**Version of the documentation**

2.4 and 2.5

**Link to Redmine ticket (if applicable)**

N/A

**Page (and section, if applicable) where the issue occurs**

https://www.accesstomemory.org/en/docs/2.4/user-manual/add-edit-content/authority-records/#add-a-new-authority-record-from-the-main-menu

https://www.accesstomemory.org/en/docs/2.4/user-manual/add-edit-content/authority-records/#add-a-new-authority-record-from-an-authority-record-view-page

**Description of the issue**

I noticed that the links to the ISAAR-CPF standard on the ICA's website are broken, because the ICA has moved the standard without adding a redirect. The correct link location is now: 

* https://www.ica.org/isaar-cpf-international-standard-archival-authority-record-corporate-bodies-persons-and-families-2nd

**Suggested fix**

Updating the current links to the new link provided above

**Comment by fiver-watson** [comment]
PR submitted by @testy-mctest : https://github.com/artefactual/atom-docs/pull/52

**Comment by fiver-watson** [comment]
Fix applied in d2fcf12d347147ae44957bfbd31a6c48ae71b9f5. Thanks again, @testy-mctest ! Closing this issue now.
