### ISSUE TITLE
Update create authority records to add subject and place access points

### ISSUE THREAD

**Issue by corinnemrogers** [artefactual/atom-docs#55]
**Version of the documentation**
2.5

**Link to Redmine ticket (if applicable)**
https://projects.artefactual.com/issues/12647

**Page (and section, if applicable) where the issue occurs**
https://www.accesstomemory.org/en/docs/2.5/user-manual/add-edit-content/authority-records/#add-access-points-to-your-authority-record

**Description of the issue**
New feature: an authorized user can now add subject and place access points to authority records - document this process with screenshots; also the current limitations of this feature

**Suggested fix**

**Comment by fiver-watson** [comment]
Fixed in https://github.com/artefactual/atom-docs/pull/60
