### ISSUE TITLE
Update instructions for ascending-descending sort feature - issue 12000

### ISSUE THREAD

**Issue by corinnemrogers** [artefactual/atom-docs#71]
**Version of the documentation**
2.5

**Link to Redmine ticket (if applicable)**
https://projects.artefactual.com/issues/12000

**Page (and section, if applicable) where the issue occurs**
https://www.accesstomemory.org/en/docs/2.5/user-manual/access-content/browse/
https://www.accesstomemory.org/en/docs/2.5/user-manual/access-content/navigate/#sort-button

**Description of the issue**
a choice of ascending or descending sort has been added to browse results

**Suggested fix**

**Comment by currmie** [comment]
Looks good!

**Comment by corinnemrogers** [comment]
1 parent baa94af commit c4932ca9e351c47d355353fddbf46de6b2c31a62
