### ISSUE TITLE
Update AtoM technical architecture page

### ISSUE THREAD

**Issue by corinnemrogers** [artefactual/atom-docs#88]
**Version of the documentation**
2.5

**Link to Redmine ticket (if applicable)**

**Page (and section, if applicable) where the issue occurs**
https://www.accesstomemory.org/en/docs/2.5/user-manual/overview/intro/

**Description of the issue**
update image, versions for PHP, ES, mySQL

**Suggested fix**

**Comment by fiver-watson** [comment]
Fixed in https://github.com/artefactual/atom-docs/commit/3d1268f873454648bf4c34159192cd7e33ab9895
